<?php if ($this->usuario->getAdministrativo()) { ?>
<fieldset>
  <legend>Permissões administrativas</legend>

  <form class="form-horizontal" 
        name="form_acoes" 
        action="<?php echo $this->baseUrl('/administrativo/usuario/set-permissao-adm') ?>">   
    <input type="hidden" name="usuario" value="<?php echo $this->usuario->getId(); ?>">
    <ul>
      <?php $oModulosAdministrador = $this->modulosAdm ?>
      <li>
        <?php echo $oModulosAdministrador->getNome() ?>
        
        <ul>
          <?php foreach ($oModulosAdministrador->getControles() as $c) { ?>
          <li>
            <?php echo $c->getNome() ?>
            <ul>
              <?php foreach ($c->getAcoes() as $a) { ?>
              <li>
                <input type="checkbox" id="acao_<?php echo $a->getId() ?>" name="acao[<?php echo $a->getId() ?>]"
                  <?php if (array_search($a->getId(), $this->permissoesAdm) !== false) echo 'checked' ?>>
                  <?php echo $a->getNome() ?>
              </li>
              <?php } ?>
            </ul>
          </li>
          <?php } ?>
        </ul>
      </li> 
    </ul>
    <div class="control-group">
      <div class="controls">
        <input type="submit" class="btn btn-success" value="Salvar" name="submit">
      </div>    
    </div>
  </form>
</fieldset>
<?php } ?>

<?php if (!empty($this->contribuintes)) { ?>
<fieldset>
  <legend>Permissões por contribuinte</legend>
  
  <form class="form-horizontal" 
        name="form_acoes" 
        action="<?php echo $this->baseUrl('/administrativo/usuario/set-permissao') ?>">    
    <input type="hidden" name="usuario" value="<?php echo $this->usuario->getId(); ?>" />
      <div class="control-group">
        <label for="contribuinte" class="control-label optional">Contribuinte</label>
        <div class="controls">
          <select name="contribuinte" 
                  id="contribuinte" 
                  ajax-url="<?php echo $this->baseUrl('/administrativo/usuario/get-permissao') ?>" 
                  style="width: 70%">
            <?php foreach ($this->contribuintes as $iCodigo => $oContribuinte) { ?>
             <option value="<?php echo $iCodigoContribuinte ?>"><?php echo $oContribuinte->nome ?></option>
            <?php } ?>
          </select>
        </div>
      </div>
    <ul>
      <?php foreach ($this->modulos as $oModulosContribuinte) { ?>
      <li>
        <?php echo $oModulosContribuinte->getNome() ?>
        
        <ul>
          <?php foreach ($oModulosContribuinte->getControles() as $oControle) { ?>
          <li><?php echo $oControle->getNome(); ?>
            <ul>
              <?php foreach ($oControle->getAcoes() as $oAcao) { ?>
              <li>
                <input type="checkbox" id="acao_<?php echo $oAcao->getId() ?>" name="acao[<?php echo $oAcao->getId() ?>]"
                  <?php if (array_search($oAcao->getId(), $this->permissoes) !== FALSE) echo 'checked' ?>>
                  <?php echo $oAcao->getNome() ?>
              </li>
              <?php } ?>
            </ul>
          </li>
          <?php } ?>
        </ul>
      </li>
      <?php } ?>  
    </ul>
    
    <div class="control-group">
      <div class="controls">
        <input type="submit" class="btn btn-success" value="Salvar" name="submit" />
      </div>    
    </div>
  </form>
</fieldset>
<?php } ?>