<ul class="inline">
  <li>
    <a href="<?php echo $this->serverUrl('/files/duvidas_frequentes.zip') ?>"
       title="<?php echo $this->translate->_('Dúvidas Frequentes') ?>">
      <img src="<?php echo $this->serverUrl('/auth/img/duvidas.png') ?>" alt="">
    </a>
    <br>
    <a href="<?php echo $this->serverUrl('/files/duvidas_frequentes.zip') ?>"
       title="<?php echo $this->translate->_('Dúvidas Frequentes') ?>">
      <?php echo $this->translate->_('Dúvidas Frequentes') ?>
    </a>
  </li>
  <li>
    <a href="<?php echo $this->serverUrl('/files/manual.pdf') ?>" target="_blank"
       title="<?php echo $this->translate->_('Manual') ?>">
      <img src="<?php echo $this->serverUrl('/auth/img/manual.png') ?>" alt="">
    </a>
    <br>
    <a href="<?php echo $this->serverUrl('/files/manual.pdf') ?>" target="_blank"
       title="<?php echo $this->translate->_('Manual') ?>">
      <?php echo $this->translate->_('Manual') ?>
    </a>
  </li>
</ul>