<ul>
  <li class='texto'>
    <?php echo $this->translate->_('Emita sua <strong>Nota Fiscal de Serviços</strong> eletronicamente de forma simples e rápida;') ?>
  </li>
  <li class='texto'>
    <?php echo $this->translate->_('Obtenha a senha de <strong>acesso</strong> junto a prefeitura de sua cidade;') ?>
  </li>
  <li class='texto'>
    <?php echo $this->translate->_('O serviço está <strong>disponível 24h</strong> por dia, 7 dias da semana;') ?>
  </li>
  <li class='texto'>
    <?php echo $this->translate->_('Pode ser acessado em <strong>qualquer lugar</strong>.') ?>
  </li>
</ul>