<fieldset>
  <legend><?php echo $this->translate->_('Guias') ?></legend>

  <table class="table table-bordered table-condensed table-striped table-hover">
    <thead>
    <tr>
      <th><?php echo $this->translate->_('Competência') ?></th>
      <th><?php echo $this->translate->_('Data Vencimento') ?></th>
      <th><?php echo $this->translate->_('Valor Corrigido') ?></th>
      <th><?php echo $this->translate->_('Valor Histórico') ?></th>
      <th><?php echo $this->translate->_('Situação') ?></th>
      <th class="table-th-acao"><?php echo $this->translate->_('Ação') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($this->oGuias) > 0) { ?>
      <?php foreach ($this->oGuias as $oGuia) {

        $oSituacaoGuia = new stdclass();

        switch ($oGuia->getSituacao()) {
          case 'a' :

            $oSituacaoGuia->sClassLabel = 'label label-warning';

            if ($this->iTipoEmissao == Contribuinte_Model_ContribuinteAbstract::TIPO_EMISSAO_NOTA) {

              $oSituacaoGuia->sUrlBotao = 'reemitir';
              $iModalHeight             = 250;
            } else {

              $oSituacaoGuia->sUrlBotao = 'reemitir-dms-guia';
              $iModalHeight             = 200;
            }
            break;
          case 'p' :
            $oSituacaoGuia->sClassLabel = 'label label-success';
            break;
          case 'c' :
            $oSituacaoGuia->sClassLabel = 'label label-important';
            break;
          case 'd' :
          case 'x' :
          default  :
            $oSituacaoGuia->sClassLabel = 'label';
        }
        ?>
        <tr>
          <td><?php echo str_pad($oGuia->getMesComp(), 2, '0', STR_PAD_LEFT) . '/' . $oGuia->getAnoComp() ?></td>
          <td><?php echo $oGuia->getVencimento()->format('d/m/Y') ?></td>
          <td><?php echo DBSeller_Helper_Number_Format::toMoney($oGuia->getValorCorrigido(), 2, 'R$ ') ?></td>
          <td><?php echo DBSeller_Helper_Number_Format::toMoney($oGuia->getValorHistorico(), 2, 'R$ ') ?></td>
          <td>
          <span class="<?php echo $oSituacaoGuia->sClassLabel ?>">
            <?php echo Contribuinte_model_guia::$SITUACAO[$oGuia->getSituacao()] ?>
          </span>
          </td>
          <td>
            <?php if (isset($oSituacaoGuia->sUrlBotao)) { ?>
              <button modal-height="<?php echo $iModalHeight; ?>"
                      modal-width="500"
                      modal-url="/contribuinte/guia/<?php echo $oSituacaoGuia->sUrlBotao ?>/guia/<?php echo $oGuia->getId() ?>"
                      data-toggle="modal"
                      role="button"
                      href="#myModal"
                      class="btn btn-mini btn-success input-mini">
                <?php echo $this->translate->_('Reemitir'); ?>
              </button>
            <?php } else { ?>
              <button class="btn btn-mini input-mini" disabled="disabled">
                <?php echo $this->translate->_('Reemitir'); ?>
              </button>
            <?php } ?>
          </td>
        </tr>
      <?php } ?>
    <?php } else { ?>
      <tr>
        <td colspan="6"><?php echo $this->translate->_('Nenhum registro encontrado.') ?></td>
      </tr>
    <?php } ?>
    </tbody>
  </table>
    <?php
    if($this->iTipoEmissao == Contribuinte_Model_ContribuinteAbstract::TIPO_EMISSAO_NOTA){
      $this->urlFor("/contribuinte/guia/consulta-emissao-nota/");
    }else if($this->iTipoEmissao == Contribuinte_Model_ContribuinteAbstract::TIPO_EMISSAO_DMS){
      $this->urlFor("/contribuinte/guia/consulta-emissao-dms/");
    }
    echo $this->paginationControl(
          $this->oGuias,
          'Sliding',
          'layouts/pager.phtml',
          array('translate' => $this->translate)
        );
  ?>
</fieldset>