<?php echo $this->headScript() ?>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 id="myModalLabel">Reemissão de Guia</h3>
</div>

<?php if ($this->mensagem_erro) { ?>
<div class="alert alert-error" style="margin:5px 5px 0">
  <a class="close" data-dismiss="alert" href="#">&times;</a>
  <?php echo $this->mensagem_erro ?>
</div>
<?php } ?>
  
<div style="text-align:center;margin:20px 5px 5px">
  <?php if (isset($this->arquivo)) { ?>
  <div class="alert alert-success">Guia emitida com sucesso!</div>
  <a class="btn btn-success" href="/default/index/get/file/<?php echo $this->arquivo ?>" target="_blank">
    Abrir guia de pagamento
  </a>
  <br><br>
  <?php } else { ?>
  <?php echo $this->form ?>
  <?php } ?>
</div>

<div class="modal-footer">
  <?php if ($this->arquivo) { ?>
  <a href="#" class="btn" id="ok-btn">Fechar</a>
  <?php } else { ?>
  <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</a>
  <a href="#" class="btn btn-success" id="fechar">Reemitir</a> 
  <?php } ?>
</div>