<?php if (count($this->guias) > 0) { ?>
<fieldset>
  <legend>Guias</legend>
  
  <table class="table table-bordered table-condensed table-striped table-hover">
    <thead>
      <tr>
        <th>Valor</th>
        <th>Data do vencimento</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->guias as $guia) { ?>
      <tr>
        <td>R$ <?php echo number_format($guia->getValorCorrigido(),2,',','.'); ?></td>
        <td><?php echo $guia->getVencimento()->format("d/m/Y"); ?></td>
        <td>
          <a href="/contribuinte/guia/notas-substituto/id/<?php echo $guia->getId() ?>" class="btn btn-success btn-small">
            Detalhes
          </a>
          <?php if ($guia->getSituacao() == Prestador_Model_Guia::$ABERTA) { ?>
          <a modal-url="/contribuinte/guia/reemitir/guia/<?php echo $guia->getId() ?>" role="button" data-toggle="modal" 
             href="#myModal" class="btn btn-small btn-success">Reemitir guia</a>
          <?php } elseif ($guia->getSituacao() == Prestador_Model_Guia::$PAGA) { ?>
          <a href="#" class="btn disabled btn-small btn-success">Paga</a>
          <?php } elseif ($guia->getSituacao() == Prestador_Model_Guia::$CANCELADA) { ?>
          <a href="#" class="btn disabled btn-small btn-success">Cancelada</a>
          <?php } ?>
        </td>
      </tr>
      <?php } ?>
    </tbody>
  </table>
</fieldset>
<?php } ?>

<?php if (count($this->notas_retidas) > 0) { ?>
<fieldset>
  <legend>Substituto tributário</legend>
  <table class="table table-striped table-condensed">
    <thead>
      <tr>
        <th></th>
        <th>Numero</th>
        <th>Competência</th>
        <th>Data da emissão</th>
        <th>Prestador</th>
        <th>Valor do ISS</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->notas_retidas as $nota) { ?>
      <tr>
        <td>
          <input type="checkbox" name="nota[<?php echo $nota->getId() ?>]" data-nota="<?php echo $nota->getId() ?>">
        </td>
        <td><?php echo $nota->getNota()                                                       ?></td>
        <td><?php echo $nota->getComp()                                                       ?></td>
        <td><?php echo $nota->formatedData() . ' ' . $nota->formatedHora()                    ?></td>
        <td><?php echo $nota->getP_razao_social()                                             ?></td>
        <td><?php echo DBSeller_Helper_Number_Format::toMoney($nota->getS_vl_iss(), 2, 'R$ ') ?></td>
      </tr>
      <?php } ?>    
    </tbody>
  </table>
  
  <div class="pull-right">
    <a id="guia-tomador" href="#" class="btn btn-success">Gerar guia</a>
  </div>
</fieldset>
<?php } ?>