<?php echo $this->oFormConsulta ?>

<fieldset>
  <legend><?php echo $this->translate->_('Resultado Pesquisa') ?></legend>
  <span class="icon-ok" style="border: 1px solid #7F7777;width:15px;height:15px;"></span>&nbsp; Contas que serão obrigatórias.
  <br /><br />
  <div id="jqGridContainer">
    <table id="jqList"></table>
    <div id="jqPager"></div>
  </div>
  <br />
  <button type="button" id="btn_salvar" class="btn btn-success">Atualizar contas obrigatórias</button>
</fieldset>