<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title><?php echo $this->translate->_('Nota Fiscal Eletrônica') ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" type="image/jpeg" href="<?php echo $this->serverUrl("/global/img/brasao.jpg?v={$this->versao}") ?>">
    <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/jquery/jquery-ui/jquery-ui-1.9.2.custom.min.css?v={$this->versao}") ?>">
    <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/twitter-bootstrap/bootstrap.min.css?v={$this->versao}") ?>">
    <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/twitter-bootstrap/bootstrap-responsive.min.css?v={$this->versao}") ?>">
    <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/twitter-bootstrap/bootstrap-combobox.css?v={$this->versao}") ?>">
    <?php echo $this->headLink() ?>

    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/jquery-1.8.3.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/ui/jquery-ui-1.9.2.custom.min.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/ui/locale/jquery.ui.datepicker-pt-BR.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/twitter-bootstrap/bootstrap.min.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/twitter-bootstrap/bootstrap-combobox.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/twitter-bootstrap/bootstrap.bootbox.min.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/cookie/jquery.cookie.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/form/jquery.form.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/maskinputmoney/jquery.maskInputMoney.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/meiomask/jquery.meiomask.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/datatables/jquery.dataTables.min.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/datatables/jquery.dataTables.extends.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/cryptojs/sha1.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/dbseller/db.jquery.extends.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/dbseller/db.getMunicipioByUfEstado.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/dbseller/db.global.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/dbseller/db.global.notificacao.js?v={$this->versao}") ?>"></script>
    <script type="text/javascript" src="<?php echo $this->serverUrl("/global/js/jquery/url/purl.js?v={$this->versao}") ?>"></script>
    <?php echo $this->headScript() ?>

  </head>
  <body>
    <div class="container">
      <?php echo $this->layout()->content ?>
    </div>

    <div class="footer">
      <?php echo $this->partial('layouts/footer.phtml', 'auth', array('oPrefeitura' => $this->oPrefeitura)) ?>
    </div>
  </body>
</html>