<?php echo $this->headScript() ?>

<div class="modal-header">
  <button type="button" class="close fechar-modal" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 id="myModalLabel">Rejeitar Cancelamento da NFSE nº <?php echo $this->solicitacao['nota'] ?></h3>
</div>

<div class="modal-body">
  <div class="ajax-errors"><!-- Dinamico --></div>
  <?php echo $this->form ?>
</div>

<div class="modal-footer">
  <button class="input-medium btn btn-danger fechar-modal"  data-dismiss="modal" aria-hidden="true">Fechar</button>
  <button class="input-medium btn btn-primary" id="confirmar">Confirmar</button>
</div>