<?php echo $this->headScript() ?>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 id="myModalLabel">NFSE - Enviar por email</h3>
</div>

<div class="modal-body">
  <div id="email_erros"><!-- Dinamico --></div>
  <?php echo $this->form ?>
</div>

<div class="modal-footer">
  <button class="input-medium btn btn-danger"  data-dismiss="modal" aria-hidden="true">Fechar</button>
  <button class="input-medium btn btn-primary" id="enviar_email">Enviar</button>
</div>