<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nota fiscal eletrônica</title>
    <link href="/global/css/twitter-bootstrap/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="/global/css/twitter-bootstrap/bootstrap-responsive.min.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="/default/css/manutencao/controller.css" media="screen" rel="stylesheet" type="text/css" >
  </head>
  <body>
    <div class="content">
      <div class="image">
        <a href="<?php echo 'http://'.$_SERVER['HTTP_HOST'] ?>" title="">
          <img src="/global/img/brasao.jpg" alt="" />
        </a>
      </div>
      
      <div class="title">
        <h3><?php echo $this->title ?></h3>
      </div>
      
      <div class="message well">
        <div class="message-text">
          <h5><?php echo $this->message ?></h5>
        </div>
        <div class="message-text text-error">
          <h5><?php echo $this->information ?></h5>
        </div>
      </div>
    </div>
    
    <div class="footer">
      <a href="http://www.dbseller.com.br/" title="">
        <img src="/global/img/logotipo-dbseller.gif" alt="" />
      </a>
    </div>
  </body>
</html>