<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="shortcut icon" type="image/jpeg" href="<?php echo $this->serverUrl("/global/img/brasao.jpg?v={$this->versao}") ?>">
  <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/jquery/jquery-ui/jquery-ui-1.9.2.custom.min.css?v={$this->versao}") ?>">
  <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/twitter-bootstrap/bootstrap.min.css?v={$this->versao}") ?>">
  <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/twitter-bootstrap/bootstrap-responsive.min.css?v={$this->versao}") ?>">
  <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/twitter-bootstrap/bootstrap-combobox.css?v={$this->versao}") ?>">
  <link media="screen" rel="stylesheet" type="text/css" href="<?php echo $this->serverUrl("/global/css/style.css?v={$this->versao}") ?>">
  <?php echo $this->headLink() ?>

</head>
<body>
<div class="content">
  <div class="image">
    <a href="<?php echo 'http://'.$_SERVER['HTTP_HOST'] ?>" title="">
      <img src="/global/img/brasao.jpg" alt="" />
    </a>
  </div>

  <div class="title">
    <h3><?php echo $this->title ?></h3>
  </div>

  <div class="message well">
    <div class="message-text">
      <h5><?php echo $this->message ?></h5>
    </div>
    <div class="message-text text-error">
      <h5><?php echo $this->information ?></h5>
    </div>
  </div>
</div>

<div class="db-footer navbar navbar-fixed-bottom">
  <?php if ($this->oPrefeitura) { ?>
    <?php
    echo "{$this->oPrefeitura->getNome()} - {$this->oPrefeitura->getMunicipio()} - {$this->oPrefeitura->getUf()}"
    ?>
    <br>
    <?php echo "{$this->oPrefeitura->getEndereco()}, {$this->oPrefeitura->getNumero()}" ?>
    <?php echo '- CEP: ' . DBSeller_Helper_Number_Format::maskCep($this->oPrefeitura->getCep()); ?>
    <br>

    <?php if ($this->oPrefeitura->getTelefone()) { ?>
      <?php echo 'Fone: ' . DBSeller_Helper_Number_Format::maskPhoneNumber($this->oPrefeitura->getTelefone()) ?>
    <?php } ?>

    <?php if ($this->oPrefeitura->getEmail()) { ?>
      <?php echo '- Email: ' . $this->oPrefeitura->getEmail() ?>
    <?php } ?>
  <?php } else { ?>

    DBSeller Serviços de Informática Ltda. - Porto Alegre - RS<br>
    Av. Júlio de Castilhos, 44 (5º Andar - Sala 501) - Centro - CEP: 90030-130<br>
    Fone: 0xx (51) 3076.5101<br>
  <?php } ?>
</div>
</body>
</html>