<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $this->translate->_('Nota Fiscal Eletrônica') ?></title>
    <link rel="shortcut icon" type="image/jpeg" href="<?php echo $this->baseUrl('/global/img/brasao.jpg') ?>">
    <link href="<?php echo $this->baseUrl('/global/css/twitter-bootstrap/bootstrap.min.css') ?>" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl('/global/css/twitter-bootstrap/bootstrap-responsive.min.css') ?>" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo $this->baseUrl('/default/css/error/controller.css') ?>" media="screen" rel="stylesheet" type="text/css" >
  </head>
  <body>
    <div class="error-content">
      <div class="error-image">
        <a href="<?php echo $this->baseUrl('/') ?>" title="<?php echo $this->translate->_('Ir para a página inicial') ?>">
          <img src="<?php echo $this->baseUrl('/global/img/brasao.jpg') ?>" alt="">
        </a>
      </div>
    
      <div class="error-title">
        <h3><?php echo $this->message_title ?></h3>
      </div>
      
      <div class="error-exception text-error well">
        <h4><?php echo $this->message_content ?></h4>
      </div>
      
      <div class="error-button">
        <a class="btn btn-inverse" href="<?php echo $this->baseUrl('/') ?>" title="<?php echo $this->translate->_('Ir para a página inicial') ?>">
          <?php echo $this->translate->_('Ir para a página inicial') ?>
        </a>
      </div>
    </div>
  </body>
</html>