<?php
$oTradutor = $this->layout()->translate;
?>

<div class="navbar">
  <div class="navbar-inner">
    <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    
    <div class="nav-collapse">
      <?php if ($this->user !== NULL) { ?>
      
      <?php echo $this->navigation(Zend_Registry::get('nav'))->menu()->setPartial('layouts/menu/navigation.phtml') ?>

      <ul class="nav pull-right">
        <li class="dropdown">
          <a id="drop3" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
            <i class="icon icon-user"></i>
            <?php echo DBSeller_Helper_String_Format::wordsCap($this->user->getNome()) ?>
            
            <!-- Se for contador mostra o nome do contribuinte escolhido -->
            <?php if ($this->contribuinte && $this->user->getLogin() !== $this->contribuinte->getCgccpf()) { ?>
            (<?php echo DBSeller_Helper_String_Format::wordsCap($this->contribuinte->getNome()) ?>)
            <?php } ?>
            
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop3" style="min-width:250px">
            <li>
              <span style="padding:0 20px;font-weight:bold">
                <i class="icon icon-user"></i> <?php echo $oTradutor->_('Informações do Usuário') ?>
              </span>
            </li>
            <li class="divider"></li>
            
            <?php if ($this->contribuinte instanceof Contribuinte_Model_Contribuinte) { ?>
            <li>
              <a href="<?php echo $this->baseUrl('/contribuinte/index/contribuinte/alterar/cliente') ?>">
                <?php echo $oTradutor->_('Alterar Contribuinte') ?>
              </a>
            </li>
            <?php } ?>
            <li>
              <a href="<?php echo $this->baseUrl('/default/index') ?>">
                <?php echo $oTradutor->_('Alterar Módulo') ?>
              </a>
            </li>

            <?php if ($this->contribuinte &&
                      DBSeller_Plugin_Auth::checkPermission('contribuinte/parametro/contribuinte')) { ?>
            <li>
              <a href="<?php echo $this->baseUrl('/contribuinte/parametro/contribuinte') ?>">
                <?php echo $oTradutor->_('Parâmetros Contribuinte') ?>
              </a>
            </li>
            <?php } ?>
           
            <?php if (is_object($this->contribuinte)) { ?>
            
            <li class="divider" style="margin-top:15px"></li>
            <li>
              <span style="padding:0 20px;font-weight:bold">
                <i class="icon icon-briefcase"></i> <?php echo $oTradutor->_('Informações do Contribuinte') ?>
              </span>
            </li>
            <li class="divider"></li>
            <li style="min-width:450px;padding-bottom:10px;">
              <div style="font-size:0.8em;padding:0 20px;color:#707070">
                <table class="menu-table-contribuinte" border="0">
                  <tr>
                    <th><?php echo $oTradutor->_('CPF / CNPJ:') ?></th>
                    <td>
                      <?php echo DBSeller_Helper_Number_Format::maskCPF_CNPJ($this->contribuinte->getCgccpf()) ?>
                    </td>
                    <?php if ($this->contribuinte->getInscricaoMunicipal()) { ?>
                    <th class="col2"><?php echo $oTradutor->_('Inscrição Municipal:') ?></th>
                    <td><?php echo $this->contribuinte->getInscricaoMunicipal() ?></td>
                    <?php } else if ($this->contribuinte->getCgm()) { ?>
                    <th class="col2" style="text-align:right !important; padding-right:10px !important">
                      <?php echo $oTradutor->_('CGM:') ?>
                    </th>
                    <td><?php echo $this->contribuinte->getCgm() ?></td>
                    <?php } ?>
                  </tr>
                  <tr>
                    <th><?php echo $oTradutor->_('Endereço:') ?></th>
                    <td colspan="3">
                      <?php
                      echo DBSeller_Helper_String_Format::wordsCap(
                        $this->contribuinte->getTipoLogradouro() . ' ' .
                        $this->contribuinte->getDescricaoLogradouro() . ', ' .
                        $this->contribuinte->getLogradouroNumero() . ' - ' .
                        $this->contribuinte->getLogradouroBairro()
                      );
                      ?>
                    </td>
                  </tr>
                  <tr>
                    <th><?php echo $oTradutor->_('Complemento:') ?></th>
                    <td colspan="3">
                      <?php
                      echo DBSeller_Helper_String_Format::wordsCap($this->contribuinte->getLogradouroComplemento())
                      ?>
                    </td>
                  </tr>
                  <tr>
                    <th><?php echo $oTradutor->_('Município / UF:') ?></th>
                    <td colspan="3">
                      <?php
                      echo DBSeller_Helper_String_Format::wordsCap(
                        $this->contribuinte->getDescricaoMunicipio()
                      ) . ' / ' . $this->contribuinte->getEstado()
                      ?>
                    </td>
                  </tr>
                  <tr>
                    <th><?php echo $oTradutor->_('Telefone:') ?></th>
                    <td colspan="3">
                      <?php echo DBSeller_Helper_Number_Format::maskPhoneNumber($this->contribuinte->getTelefone()) ?>
                    </td>
                  </tr>
                  
                  <?php
                  if ($this->contribuinte instanceof Contribuinte_Model_Contribuinte) {

                    $bIsSimplesNacional = Contribuinte_Model_Contribuinte::getInformacaoContribuinteAtual($this->contribuinte, 'optante_simples_nacional');

                    // Verifica o regime tributário considerando a regra do simples
                    if ($bIsSimplesNacional == 1) {
                      $sDescRegime = Contribuinte_Model_Contribuinte::getCategoriaSimplesByCodigo($this->contribuinte->getOptanteSimplesCategoria());
                    } else {
                      $sDescRegime = Contribuinte_Model_Contribuinte::getRegimeTributarioByCodigo($this->contribuinte->getRegimeTributario());
                    }
                  ?>
                  <tr>
                    <td colspan="4"><hr style="margin:5px 0"></td>
                  </tr>
                  <tr>
                    <th class="col2"><?php echo $oTradutor->_('Simples:') ?></th>
                    <td>
                      <?php echo ($bIsSimplesNacional == 1) ? 'Sim' : 'Não'; ?>
                    </td>
                    <th class="col2">Substituto Tributário:</th>
                    <td><?php echo $this->contribuinte->getDescricaoSubstituicaoTributaria()?></td>
                  </tr>
                  <tr>
                    <th><?php echo $oTradutor->_('Exigível:') ?></th>
                    <td><?php echo $this->contribuinte->getDescricaoExigibilidade()?></td>
                    <th class="col2"><?php echo $oTradutor->_('Incentivo:') ?></th>
                    <td><?php echo $this->contribuinte->getDescricaoIncentivoFiscal() ?></td>
                  </tr>
                  <tr>
                    <th><?php echo $oTradutor->_('Regime:') ?></th>
                    <td><?php echo $sDescRegime; ?></td>
                    <th class="col2"><?php echo $oTradutor->_('Empresa:') ?></th>
                    <td>
                      <?php 
                      echo DBSeller_Helper_String_Format::wordsCap(
                        $this->contribuinte->getDescricaoTipoClassificacao()
                      )
                      ?>
                    </td>
                  </tr>
                  <tr>
                    <th class="col2"><?php echo $oTradutor->_('Tipo de Emissão:') ?></th>
                    <td colspan="3">
                      <?php echo DBSeller_Helper_String_Format::wordsCap($this->contribuinte->getDescricaoTipoEmissao()) ?>
                    </td>
                  </tr>
                  
                  <?php } ?>
                  
                </table>
              </div>
            </li>
            <?php } ?>
          </ul>
        </li>
        <!-- Notificações do sistema-->
        <?php echo $this->partial('notificacao/listar.phtml', 'global', array('translate' => $oTradutor)) ?>
        <li class="divider-vertical"></li>
        <li>
          <a href="<?php echo $this->baseUrl('/auth/logout') ?>">
            <i class="icon icon-off"></i> <?php echo $oTradutor->_('Logout') ?>
          </a>
        </li>
      </ul>
      <?php } ?>
    </div><!--/.nav-collapse -->
  </div><!--/.nav-inner -->
</div><!--/.navbar -->