<?php $oTradutor = $this->layout()->translate ?>
<div class="navbar">
  <div class="navbar-inner">
  <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </a>
<?php if ($this->user !== null) { ?>
    <div class="nav-collapse">
      <ul class="nav pull-right">
        <li class="dropdown">
          <a id="drop3" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
            <i class="icon icon-user"></i>
            <?php echo DBSeller_Helper_String_Format::wordsCap($this->user->getNome()) ?>
            <?php
            echo ($this->contribuinte) ?
              '('.DBSeller_Helper_String_Format::wordsCap($this->contribuinte->getNome()).')' :
              NULL;
            ?>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop3" style="min-width:250px">
            <li>
              <span style="padding:0 20px;font-weight:bold">
                <i class="icon icon-user"></i> Informações do Usuário
              </span>
            </li>
            <li class="divider"></li>
            <li><a href="<?php echo $this->baseUrl('/default/index') ?>">Alterar Módulo</a></li>
            <li><a href="<?php echo $this->baseUrl('/administrativo/usuario/trocar-senha') ?>">Alterar Senha</a></li>
            
            <?php if ($this->contribuinte && DBSeller_Plugin_Auth::checkPermission('contribuinte/parametro/contribuinte')) { ?>
            <li>
              <a href="/<?php echo $this->baseUrl('contribuinte/parametro/contribuinte') ?>">
                Parâmetros Contribuinte
              </a>
            </li>
            <?php } ?>
           
            <?php if (is_object($this->contribuinte)) { ?>
            
            <li class="divider" style="margin-top:15px"></li>
            <li>
              <span style="padding:0 20px;font-weight:bold">
                <i class="icon icon-briefcase"></i> Informações do Contribuinte
              </span>
            </li>
            <li class="divider"></li>
            <li style="min-width:450px;padding-bottom:10px;">
              <div style="font-size:0.8em;padding:0 20px;color:#707070">
                <table class="menu-table-contribuinte">
                  <tr>
                    <th>CPF/CNPJ:</th>
                    <td><?php echo DBSeller_Helper_Number_Format::maskCPF_CNPJ($this->contribuinte->getCgccpf()) ?></td>
                    <th class="col2">Inscrição Municipal:</th>
                    <td><?php echo $this->contribuinte->getInscricaoMunicipal(); ?></td>
                  </tr>
                  <tr>
                    <th>Endereço:</th>
                    <td colspan="3">
                      <?php
                      echo DBSeller_Helper_String_Format::wordsCap($this->contribuinte->getTipoLogradouro() . ' ' .
                                                                   $this->contribuinte->getDescricaoLogradouro() . ', ' .
                                                                   $this->contribuinte->getLogradouroNumero() . ' - ' .
                                                                   $this->contribuinte->getLogradouroBairro());
                      ?>
                    </td>
                  </tr>
                  <tr>
                    <th>Complemento:</th>
                    <td colspan="3">
                      <?php echo DBSeller_Helper_String_Format::wordsCap($this->contribuinte->getLogradouroComplemento()) ?>
                    </td>
                  </tr>
                  <tr>
                    <th>Município / UF:</th>
                    <td colspan="3">
                      <?php echo DBSeller_Helper_String_Format::wordsCap($this->contribuinte->getDescricaoMunicipio()) . ' / ' .
                                                                         $this->contribuinte->getEstado() ?>
                    </td>
                  </tr>
                  <tr>
                    <th>Telefone:</th>
                    <td colspan="3"><?php echo $this->contribuinte->getTelefone() ?></td>
                  </tr>
                  <tr>
                    <td colspan="4"><hr style="margin:5px 0"></td>
                  </tr>
                  
                  <?php if ($this->contribuinte instanceof Contribuinte_Model_Contribuinte) { ?>
                  <tr>
                    <th>Simples:</th>
                    <td><?php echo $this->contribuinte->getDescricaoOptanteSimples() ?></td>
                    <th class="col2">Substituto Tributário:</th>
                    <td><?php echo $this->contribuinte->getDescricaoSubstituicaoTributaria() ?></td>
                  </tr>
                  <tr>
                    <th>Exigível:</th>
                    <td><?php echo $this->contribuinte->getDescricaoExigibilidade() ?></td>
                    <th class="col2">Incentivo:</th>
                    <td><?php echo $this->contribuinte->getDescricaoIncentivoFiscal() ?></td>
                  </tr>
                  <tr>
                    <th>Regime:</th>
                    <td><?php echo $this->contribuinte->getDescricaoTipoClassificacao() ?></td>
                    <th class="col2">Empresa:</th>
                    <td>
                      <?php echo DBSeller_Helper_String_Format::wordsCap(
                        $this->contribuinte->getDescricaoTipoClassificacao()) ?>
                    </td>
                  </tr>
                  <tr>
                    <th>Tipo de Emissão:</th>
                    <td colspan="3">
                      <?php echo DBSeller_Helper_String_Format::wordsCap(
                        $this->contribuinte->getDescricaoTipoEmissao()
                      ) ?>
                    </td>
                  </tr>
                  
                  <?php } ?>
                </table>
              </div>
            </li>
            <?php } ?>
          </ul>
        </li>
        
        <?php if($this->qtd_notificacao) { ?>
        <li>
          <a href="<?php echo $this->baseUrl('/default/index/notificacoes') ?>">
            <span class="badge badge-important"><?php echo $this->qtd_notificacao ?></span>
          </a>
        </li>
        <?php } ?>
        <!-- Notificações do sistema-->
        <?php echo $this->partial('notificacao/listar.phtml', 'global', array('translate' => $oTradutor)) ?>
        <li class="divider-vertical"></li>
        <li>
          <a href="<?php echo $this->baseUrl('/auth/logout') ?>">
            <i class="icon icon-off"></i> <?php echo $oTradutor->_('Logout') ?>
          </a>
        </li>
      </ul>
    </div>
<?php } ?>
  </div>
</div>