<!-- View utilizada como modal -->

<?php echo $this->headScript() ?>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 id="myModalLabel">Cadastro de Empresa</h3>
</div>

<div class="modal-body">
  <?php echo $this->form ?>
</div>

<div class="modal-footer">
  <button class="btn btn-danger  input-medium" data-dismiss="modal" aria-hidden="true">Fechar</button>
  <button class="btn btn-primary input-medium" id="enviaEmpresa">Cadastrar</button>
</div>