<style type="text/css">
    table {
        border: solid 1px #000;        
        text-align: center;
        border-collapse: collapse;
        width: 100%;
        font-size: 11px;
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    }    
</style>

<table>
    <tr>
        <td rowspan="4" style="border-right: none;">
            <img src="img/brasao.jpg" />
        </td>
        <td rowspan="4" colspan="3" style="width: 80%; border: solid 1px #000;">
            PREFEITURA MUNICIPAL DE ALEGRETE<br/>
            Secretaria Municipal de Fazenda e Planejamento<br/>
    <u>NOTA FISCAL DE SERVIÇO ELETRÔNICA - NFS-e</u>
</td>
<td style="border: solid 1px #000;">Número da nota<br/>
    <?php echo $this->nota->getNota(); ?>
</td>
</tr>
<tr>
    <td style="border: solid 1px #000; width: 20%;">Data e hora de Emissão<br/>
        <?php echo $this->nota->formatedData(); ?> -
        <?php echo $this->nota->formatedHora(); ?>
    </td>
</tr>
<tr>
    <td style="border: solid 1px #000;">Código de Verificação
        <?php echo $this->nota->getCod_verificacao(); ?>
    </td>
</tr>
<tr>
    <td style="border: solid 1px #000;">Competência<br/>
        <?php echo $this->nota->getComp(); ?>
    </td>
</tr>
</table>
<table>
    <tr>
        <td colspan="5" style="border: solid 1px #000;"><b>PRESTADOR DE SERVIÇO</b></td>
    </tr>
    <tr>
        <td style="border-right: none; width: 100px" rowspan="5">&nbsp;</td>
        <td style="text-align: left;">CPF/CNPJ: <?php echo $this->nota->getP_cnpjcpf(); ?></td>
        <td style="text-align: left;">IM: <?php echo $this->nota->getP_im(); ?></td>
        <td style="text-align: left;">IE: <?php echo $this->nota->getP_ie(); ?></td>
        <td style="text-align: left;">Telefone: <?php echo $this->nota->getP_telefone(); ?></td>
    </tr>
    <tr style="border: none;">
        <td colspan="4" style="text-align: left;">Razão Social: <?php echo $this->nota->getP_razao_social(); ?></td>
    </tr>
    <tr style="border: none;">
        <td colspan="4" style="text-align: left;">Nome fantasia: <?php echo $this->nota->getP_nome_fantasia(); ?></td>
    </tr>
    <tr style="border: none;">
        <td colspan="3" style="text-align: left;">Endereço: <?php echo $this->nota->getP_endereco(); ?></td>
        <td style="text-align: left;">CEP: <?php echo $this->nota->getP_cep(); ?></td>
    </tr>
    <tr style="border: none;">
        <td colspan="4" style="text-align: left;">Complemento: <?php echo $this->nota->getP_endereco_comp(); ?></td>
    </tr>
    <tr style="border: none;">
        <td colspan="3" style="text-align: left;">Município: <?php echo $this->nota->getPrestadorMunicipio(); ?>/<?php echo $this->nota->getP_uf(); ?></td>
        <td style="text-align: left;">Email: <?php echo $this->nota->getP_email(); ?></td>
    </tr>
    <tr>
        <td colspan="5" style="border: solid 1px #000;"><b>TOMADOR DE SERVIÇO</b></td>
    </tr>
    <tr style="border: none;">
        <td style="text-align: left;" colspan="2">CPF/CNPJ: <?php echo $this->nota->getT_cnpjcpf(); ?></td>
        <td style="text-align: left;" colspan="2">IM: <?php echo $this->nota->getT_im(); ?></td>
        <td style="text-align: left;">IE: <?php echo $this->nota->getT_ie(); ?></td>
        
    </tr>
    <tr>
      <td colspan="5" style="text-align: left;">Razão Social: <?php echo $this->nota->getT_razao_social(); ?></td>  
    </tr>
    <tr style="border: none;">
        <td colspan="4" style="text-align: left;">Nome fantasia: <?php echo $this->nota->getT_nome_fantasia(); ?></td>
        <td style="text-align: left;">Telefone: <?php echo $this->nota->getT_telefone(); ?></td>
    </tr>
    <tr style="border: none;">
        <td colspan="3" style="text-align: left;">Endereço: <?php echo $this->nota->getT_endereco(); ?></td>
        <td colspan="2" style="text-align: left;">CEP: <?php echo $this->nota->getT_cep(); ?></td>
    </tr>
    <tr style="border: none; text-align: left;">
        <td colspan="5" style="text-align: left;">Complemento: <?php echo $this->nota->getT_endereco_comp(); ?></td>
    </tr>
    <tr style="border: none; text-align: left;">
        <td colspan="3" style="text-align: left;">Município: <?php echo $this->nota->getTomadorMunicipio(); ?>/<?php echo $this->nota->getT_uf(); ?></td>
        <td style="text-align: left;" colspan="2">Email: <?php echo $this->nota->getT_email(); ?></td>
    </tr>
</table>
<table>
    <tr>
        <td colspan="6" style="border: solid 1px #000;"><b>DISCRIMINAÇÃO DO SERVIÇO</b></td>
    </tr>
    <tr>
        <td colspan="6" style="border: solid 1px #000; height: 160px; overflow: hidden; vertical-align: top; text-align: left;"><?php echo $this->nota->getS_dados_discriminacao(); ?></td>
    </tr>
    <tr>
        <td colspan="6" style="border: solid 1px #000; text-align: left;">
            Local da prestação do serviço:<br/>
            <?php echo $this->nota->getServicoMunicipio(); ?>
        </td>
    </tr>
    <tr>
        <td colspan="6" style="border: solid 1px #000; text-align: left;">
            Código do serviço (Lei 116):<br/>
            <?php echo $this->nota->getS_dados_item_lista_servico(); ?> - 
            <?php echo $this->nota->getDescricaoListaServico(); ?>
        </td>
    </tr>
    <tr>
        <td colspan="6" style="border: solid 1px #000; text-align: left;">
            Código do serviço (CNAE):<br/>
            <?php echo $this->nota->getS_dados_cod_cnae(); ?>
        </td>
    </tr>   
    <tr>
        <td style="border: solid 1px #000;">Base de cálculo R$<?php echo number_format($this->nota->getS_vl_bc(), 2, ',', '.'); ?></td>
        <td style="border: solid 1px #000;">PIS R$<?php echo number_format($this->nota->getS_vl_pis(), 2, ',', '.'); ?></td>
        <td style="border: solid 1px #000;">COFINS R$<?php echo number_format($this->nota->getS_vl_cofins(), 2, ',', '.') ?></td>
        <td style="border: solid 1px #000;">INSS R$<?php echo number_format($this->nota->getS_vl_inss(), 2, ',', '.'); ?></td>               
        <td style="border: solid 1px #000;">IR R$<?php echo number_format($this->nota->getS_vl_ir(), 2, ',', '.'); ?></td> 
        <td style="border: solid 1px #000;">CSLL R$<?php echo number_format($this->nota->getS_vl_csll(), 2, ',', '.'); ?></td>        
    </tr>
    <tr>
        <td style="border: solid 1px #000;">Deduções R$<?php echo number_format($this->nota->getS_vl_deducoes(), 2, ',', '.'); ?></td>        
        <td style="border: solid 1px #000;">Aliquota <?php echo number_format($this->nota->getS_vl_aliquota(), 2, ',', '.'); ?>%</td>
        <td style="border: solid 1px #000;">ISS Retido R$<?php echo number_format($this->nota->getS_vl_iss(), 2, ',', '.'); ?></td>
        <td style="border: solid 1px #000;">Desc. Condicionais R$<?php echo number_format($this->nota->getS_vl_condicionado(), 2, ',', '.'); ?></td>></td>
        <td style="border: solid 1px #000;">Desc. Incondicionais R$<?php echo number_format($this->nota->getS_vl_desc_incondicionado(), 2, ',', '.'); ?></td>></td>
        <td style="border: solid 1px #000;">Outras retenções R$<?php echo number_format($this->nota->getS_vl_outras_retencoes(), 2, ',', '.'); ?></td>></td>
    </tr>
    <tr>
        <td colspan="6" style="border: solid 1px #000; font-weight: bold;">Valor da nota R$<?php echo number_format($this->nota->getS_vl_servicos(), 2, ',', '.'); ?></td>        
    </tr>
</table>
