<?php
  echo $this->oFormProcedimentoAlteracaoRegimeNotaSimples;
?>
<div id="alert" class="alert hidden">
</div>
<script type="text/javascript" charset="utf-8" async defer>
  $('#btn_processar').prop("disabled", false);
</script>
<div id="cadastro-simples">
<fieldset>
  <legend><?php echo $this->translate->_('Cadastro Simples') ?></legend>
    <table class="table table-bordered table-condensed table-striped table-hover" style="table-layout:fixed">
    <thead>
      <tr>
        <th class="text-center db-consulta-coluna01"><?php echo $this->translate->_('Data Início') ?></th>
        <th class="text-right  db-consulta-coluna02"><?php echo $this->translate->_('Data Baixa') ?></th>
        <th class="text-center db-consulta-coluna03"><?php echo $this->translate->_('Categoria') ?></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    </table>
  </fieldset>
</div>
<div id="retorno-processamento">
<fieldset>
  <legend><?php echo $this->translate->_('Resultado do Processamento') ?></legend>
    <table class="table table-bordered table-condensed table-striped table-hover" style="table-layout:fixed">
    <thead>
      <tr>
        <th class="text-center db-consulta-coluna01"><?php echo $this->translate->_('Competências Alteradas') ?></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    </table>
  </fieldset>
</div>