<p>Caro (a) <strong>Contribuinte</strong>,</p>
<p>
  Vimos através deste, renovar os votos de apreço e informar-lhe que para liberar seu acesso as facilidades do 
  Portal da NFs-e, deverá clicar no link:
</p>
<p>
  <a href="<?php echo $this->sLinkSenha ?>" title="Link para geração de Senha"><?php echo $this->sLinkSenha ?></a>
</p>
<p>
  <strong>Qualquer problema entre em contato com a Prefeitura.</strong>
</p>