<?php echo $this->headScript() ?>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 id="myModalLabel"><?php echo $this->translate->_('Novo Módulo') ?></h3>
</div>

<div class="modal-body"><?php echo $this->formModulo ?></div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate->_('Fechar') ?></button>
  <button class="btn btn-primary" id="envia-modulo"><?php echo $this->translate->_('Cadastrar') ?></button>
</div>