<?php echo $this->headScript() ?>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3 id="myModalLabel">Novo Controle</h3>
</div>

Para o módulo <b><?php echo $this->modulo->getNome(); ?></b>

<div class="modal-body"><?php echo $this->form ?></div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
  <button class="btn btn-primary" id="envia-controle">Cadastrar</button>
</div>