<p>Caro (a) <strong>Usuário</strong>,</p>
<p>
  Segue em anexo o relatório do protocolo gerado pelo sistema,
  referente ao serviço processado <strong>"<?php echo $this->oDadosProtocolo->getSistema() ?>"</strong>.
</p>
<p>Informamos ainda que a mesma encontra-se em formato PDF.</p>
<p>
  Para que possa visualizar é necessário que tenha instalado em seu computador o ADOBE READER, 
  caso não possua poderá acessar o link para instalação: 
  <a href="http://get.adobe.com/br/reader/">http://get.adobe.com/br/reader/</a>
</p>

<br />

<p style="font-weight:bold;color:#f00">
  <strong>*Favor não responder este e-mail.</strong>
</p>