<?php

$oTranslate = Zend_Registry::get('Zend_Translate');

$html[] = '<ul class="nav">';
 
foreach ($this->container as $page) {
  
  if (!$page->isVisible()) {
    continue;
  }
  
  // dropdown
  $dropdown = !empty($page->pages);
 
  // header
  $html[] = '<li' . ($dropdown ? ' class="dropdown"' : '') . '>';
  $html[] = '<a href="'.($dropdown ? '#' : $page->getHref()).'" '.' class="dropdown-toggle" data-toggle="dropdown">';
  $html[] = $oTranslate->_($page->getLabel());
 
  if ($dropdown) {
    $html[] = '<b class="caret"></b>';
  }
 
  $html[] = '</a>';
  
  if (!$dropdown) {
    
    $html[] = '</li>';
    continue;
  }
 
  $html[] = '<ul class="dropdown-menu">';
 
  foreach ($page->pages as $subpage) {
    
    if (!$subpage->isVisible()) {
      continue;
    }
    
    if (!DBSeller_Plugin_Auth::checkPermission(
      "{$subpage->getModule()}/{$subpage->getController()}/{$subpage->getAction()}")
    ) {
      continue;
    }
    
    if ($subpage->getLabel() == 'divider') {
      $html[] = '<li class="divider"></li>';
      continue;
    }
    
    $html[] = '<li' . ($subpage->isActive() ? ' class="active"' : '') . '>';
    $html[] = '<a href="' . $subpage->getHref() . '">';
    
    if ($subpage->get('icon')) {
      $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
    }
 
    $html[] = $subpage->getLabel();
    $html[] = "</a>";
    $html[] = "</li>";
  }
 
  $html[] = "</ul>";
  $html[] = "</li>";
}

$html[] = '</ul>';

echo join(PHP_EOL, $html);