<fieldset id="fieldset-importacao">
  <legend><?php echo $this->translate->_('Importar Arquivo') ?></legend>
  
  <div class="pull-right">
    <a href="<?php echo $this->baseUrl('/files/manual_importacao_abrasf_1-0.pdf') ?>" 
       class="btn btn-primary btn-mini" 
       target="_blank">
      <i class="icon-white icon-question-sign"></i> <?php echo $this->translate->_('Documentação') ?>
    </a>
  </div>
  
  <br>
  
  <?php echo $this->oForm ?>
</fieldset>